In [2]:
import numpy as np

In [4]:
arr = np.arange(0,11)

In [5]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
arr[10]

np.int64(10)

In [12]:
arr[1:5]

array([1, 2, 3, 4])

In [13]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [14]:
arr[:5]

array([0, 1, 2, 3, 4])

In [15]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
arr[0:5] = 100

In [17]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [18]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
slice_of_arr = arr[:5]

In [20]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [21]:
 slice_of_arr[:] = 99

In [22]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [23]:
arr_copy = arr.copy()

In [24]:
arr_copy[:]=100

In [25]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [26]:
arr_2d  = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [27]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
arr_2d.shape

(3, 3)

In [29]:
arr_2d[0]

array([1, 2, 3])

In [30]:
arr_2d[2]

array([7, 8, 9])

In [31]:
arr_2d[2,1]

np.int64(8)

In [32]:
arr_2d[2][1]

np.int64(8)

In [33]:
arr_2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
arr_2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [35]:
arr = np.arange(1, 11)

In [36]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
bool_arr = arr>4

In [41]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [42]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [8]:
dice_rolls = np.array([3, 1, 5, 2, 5, 1, 1, 5, 1, 4, 2, 1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6, 3, 6, 2, 3, 5, 6, 5])

total_rolls_over_two = dice_rolls[dice_rolls>2].size

total_rolls_over_two

19