In [3]:
import numpy as np

In [4]:
mylist = [1, 2, 4]
type(mylist)

list

In [5]:
myarr = np.array(mylist)

In [6]:
type(myarr)

numpy.ndarray

In [7]:
my_matrix = [[0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4]]

In [8]:
my_matrix


[[0, 1, 2, 3, 4],
 [0, 1, 2, 3, 4],
 [0, 1, 2, 3, 4],
 [0, 1, 2, 3, 4],
 [0, 1, 2, 3, 4]]

In [1]:
np.array(my_matrix)

NameError: name 'np' is not defined

In [10]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [12]:
np.arange(0, 101, 2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.ones((4, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [17]:
np.linspace(0, 10, 9)

array([ 0.  ,  1.25,  2.5 ,  3.75,  5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [18]:
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [19]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
np.random.rand(1)

array([0.84394362])

In [22]:
np.random.rand(1, 10)

array([[0.58628225, 0.73379207, 0.57801841, 0.44154093, 0.99754925,
        0.28798942, 0.14891909, 0.91566313, 0.12026286, 0.93205997]])

In [23]:
np.random.rand(1, 3)

array([[0.12955405, 0.819173  , 0.70613618]])

In [24]:
np.random.randn(10)

array([ 1.18806194,  0.45353004, -2.62884859, -0.45814675,  1.53868091,
        0.29247187, -1.78262613,  0.53347214,  0.13297259, -0.25744311])

In [26]:
np.random.randint(0, 10, (1, 6))

array([[7, 2, 2, 4, 6, 3]], dtype=int32)

In [27]:
np.random.randint(0, 10, (6,1))

array([[4],
       [8],
       [7],
       [4],
       [9],
       [1]], dtype=int32)

In [30]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])